# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cccc < Formula
  desc "CLI tool for cleaning up Claude Code configuration"
  homepage "https://github.com/mkoepf/claude-code-config-cleaner"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkoepf/claude-code-config-cleaner/releases/download/v0.2.0/cccc_0.2.0_darwin_amd64.tar.gz"
      sha256 "a92c91e17b62b5ae23d8c1e49c16de6406d79c29ae8478db4609dc9f845842a6"

      def install
        bin.install "cccc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkoepf/claude-code-config-cleaner/releases/download/v0.2.0/cccc_0.2.0_darwin_arm64.tar.gz"
      sha256 "b86592f8cd01a044ad819f4be031073afbf31cb4d9ff198283cb30fa6791af92"

      def install
        bin.install "cccc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkoepf/claude-code-config-cleaner/releases/download/v0.2.0/cccc_0.2.0_linux_amd64.tar.gz"
      sha256 "af9628168ae558b008c61c199c82b04f274684e5cc3d5148a62657c343178ef7"
      def install
        bin.install "cccc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkoepf/claude-code-config-cleaner/releases/download/v0.2.0/cccc_0.2.0_linux_arm64.tar.gz"
      sha256 "0faef1341dfc98fb8736f81de0e05781fa50778afb57c15cbd556c739c6c4cec"
      def install
        bin.install "cccc"
      end
    end
  end

  test do
    system "#{bin}/cccc", "--help"
  end
end
