# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cccc < Formula
  desc "CLI tool for cleaning up Claude Code configuration"
  homepage "https://github.com/mkoepf/claude-code-config-cleaner"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkoepf/claude-code-config-cleaner/releases/download/v0.1.0/cccc_0.1.0_darwin_amd64.tar.gz"
      sha256 "91f6b40f4b10d1369962d9575be0731680b248ac73f861a02dbc77a94fbc95fe"

      def install
        bin.install "cccc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkoepf/claude-code-config-cleaner/releases/download/v0.1.0/cccc_0.1.0_darwin_arm64.tar.gz"
      sha256 "2994b15ec615540d7d01eaa033815e35b5c06ba23d04eccd9a416cffcf25dcfb"

      def install
        bin.install "cccc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkoepf/claude-code-config-cleaner/releases/download/v0.1.0/cccc_0.1.0_linux_amd64.tar.gz"
      sha256 "c1b54350d8c0745ccf544f87817fdf8a6df0f4c87bff34d0861b518baded82ec"
      def install
        bin.install "cccc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkoepf/claude-code-config-cleaner/releases/download/v0.1.0/cccc_0.1.0_linux_arm64.tar.gz"
      sha256 "71f2cca55eb6e3a7925234921bb77da483fd2f418aa6e0fbbecc5b1983f9099a"
      def install
        bin.install "cccc"
      end
    end
  end

  test do
    system "#{bin}/cccc", "--help"
  end
end
