# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghcrctl < Formula
  desc "CLI tool for managing GitHub Container Registry"
  homepage "https://github.com/mkoepf/ghcrctl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkoepf/ghcrctl/releases/download/v0.1.0/ghcrctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "9bdc6d9996cc61e6635c90050f8356a10a7d6939a42c7930e2525c866defa6f4"

      def install
        bin.install "ghcrctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkoepf/ghcrctl/releases/download/v0.1.0/ghcrctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "0d7af2770fbd8de5ce6b136d1d0ae17c42dbe862fcf80f139bfc6b8961b7ce01"

      def install
        bin.install "ghcrctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkoepf/ghcrctl/releases/download/v0.1.0/ghcrctl_0.1.0_linux_amd64.tar.gz"
      sha256 "d9fbbf517662d558035d3d44836431fdca24b4d0fbd669adaa96e98de7f99084"
      def install
        bin.install "ghcrctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkoepf/ghcrctl/releases/download/v0.1.0/ghcrctl_0.1.0_linux_arm64.tar.gz"
      sha256 "ad5aee3be8cf13867c20252df181875c2db9a8b46355627c177f2dbe0bee2c96"
      def install
        bin.install "ghcrctl"
      end
    end
  end

  test do
    system "#{bin}/ghcrctl", "--version"
  end
end
